### ISSUE TITLE
Remove (or autodetect) base64 encodings/decodings

### ISSUE THREAD

**Issue by jlowellwofford** [hpc/kraken-dashboard#31]
Kraken no longer base64 encodes ips, macs, and uuids in the restapi.  This breaks the dashboard badly.  I just get a blank screen.  The console shows:

```console
2.7b3fa0db.chunk.js:2 DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at _ (http://192.168.57.10/static/js/main.050dec14.chunk.js:1:13213)
    at Y (http://192.168.57.10/static/js/main.050dec14.chunk.js:1:13514)
    at te (http://192.168.57.10/static/js/main.050dec14.chunk.js:1:18808)
    at pa (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:808877)
    at Ps (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:854313)
    at Dl (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:839833)
    at Ml (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:839758)
    at _l (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:837078)
    at http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:795156
    at t.unstable_runWithPriority (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:870278)
gs @ 2.7b3fa0db.chunk.js:2
42.7b3fa0db.chunk.js:2 DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at _ (http://192.168.57.10/static/js/main.050dec14.chunk.js:1:13213)
    at Y (http://192.168.57.10/static/js/main.050dec14.chunk.js:1:13514)
    at ne (http://192.168.57.10/static/js/main.050dec14.chunk.js:1:19619)
    at pa (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:808877)
    at Ps (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:854313)
    at Dl (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:839833)
    at Ml (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:839758)
    at _l (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:837078)
    at http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:795156
    at t.unstable_runWithPriority (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:870278)
gs @ 2.7b3fa0db.chunk.js:2
main.050dec14.chunk.js:1 Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at _ (http://192.168.57.10/static/js/main.050dec14.chunk.js:1:13213)
    at Y (http://192.168.57.10/static/js/main.050dec14.chunk.js:1:13514)
    at te (http://192.168.57.10/static/js/main.050dec14.chunk.js:1:18808)
    at pa (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:808877)
    at Ps (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:854313)
    at Dl (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:839833)
    at Ml (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:839758)
    at _l (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:837078)
    at http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:795156
    at t.unstable_runWithPriority (http://192.168.57.10/static/js/2.7b3fa0db.chunk.js:2:870278)
DevTools failed to load SourceMap: Could not parse content for http://192.168.57.10/static/js/2.7b3fa0db.chunk.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for http://192.168.57.10/static/js/main.050dec14.chunk.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for http://192.168.57.10/static/css/main.ce8a1b51.chunk.css.map: Unexpected token < in JSON at position 0
```

**Comment by kpelzel** [comment]
resolved by https://github.com/hpc/kraken-dashboard/pull/32
